#!/bin/sh
update_config()
{
	sed -i "s/^$1: .*/$1: $2/" "$config_txt"
}
config_txt="config.txt"
if [ "$1" ]; then
	meeting_number="$1"
else
	meeting_number=`sed -n 's/meeting_number: //p' $config_txt`
fi
meeting_token=`curl -sH 'Content-Type: application/json' -d "{ \"role\": 1, \"expirationSeconds\": 172799, \"meetingNumber\": $meeting_number }" http://localhost:4000 | jq -r .signature -`
update_config meeting_number "$meeting_number"
update_config token "$meeting_token"
cp "$config_txt" bin/